version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "3500:3500"
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bibliotecaPersonal
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "5500:5500"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:
