version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3500:3500"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "5500:5500"
    volumes:
      - ./frontend:/app
    restart: always
